name: Playwright Tests
on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  ui-test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: ['chromium', 'webkit', 'firefox']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps ${{ matrix.browser }}
      - name: Run Playwright tests
        run: npx playwright test --project "${{ matrix.browser }}"
      - name: Upload Allure results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-results-${{ matrix.browser }}
          path: allure-results/
          retention-days: 3

  api-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test --project "api"
      - name: Upload Allure results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-results-api
          path: allure-results/
          retention-days: 3

  generate-allure-report:
    runs-on: ubuntu-latest
    needs: [ui-test, api-test]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: allure-results-chromium
          path: allure-results/
      - uses: actions/download-artifact@v4
        with:
          name: allure-results-webkit
          path: allure-results/
      - uses: actions/download-artifact@v4
        with:
          name: allure-results-firefox
          path: allure-results/
      - uses: actions/download-artifact@v4
        with:
          name: allure-results-api
          path: allure-results/
      - name: Install Allure reports
        run: |
          npm install -D allure-commandline
          npx allure generate ./allure-results --clean
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-report
          path: allure-report/
          retention-days: 3
